services:
  kratos-migrate:
    depends_on: [ 'database' ]
    image: 'oryd/kratos:v0.10.1'
    environment:
      - DSN=postgres://forge:password@database:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: ./docker/services/kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks: ['kratos-demo']

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v0.10.1
    ports:
      - '4455:4455'
    environment:
      - PORT=4455
      - SECURITY_MODE=
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
    restart: on-failure
    networks: [ 'kratos-demo' ]

  kratos:
    depends_on: [ 'kratos-migrate' ]
    image: 'oryd/kratos:v0.10.1'
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    environment:
      - DSN=postgres://forge:password@database:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    volumes:
      - type: bind
        source: ./docker/services/kratos
        target: /etc/config/kratos
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    restart: unless-stopped
    networks: ['kratos-demo']

  mailslurper:
    image: 'oryd/mailslurper:latest-smtps'
    networks: ['kratos-demo']
    ports:
      - '4436:4436'
      - '4437:4437'

